eureka:
  client:
    eureka-server-u-r-l-context: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: springcloud-zuul
zuul:
  routes:
    api-userOne:
      path: /api-userOne/**
      serviceId: SPRINGCLOUD-CONSUMER-RIBBON
    api-userTwo:
      path: /api-userTwo/**
      serviceId: SPRING-CONSUMER-FEIGN